version: '3.9'

services:
  redis:
    container_name: redis
    image: redis:v1
    build: ./redis
    hostname: redis
    ports:
      - "6379:6379"

  sensors:
    container_name: sensors
    links:
      - redis
    build:
      context: ./sensors/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
      - "8090:8090"

  analyzer:
    container_name: analyzer
    links:
      - redis
    build:
      context: ./analyzer/
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
      - "8091:8091"
